export const colors = {
  bg: 'var(--color-bg)',
  surface: 'var(--color-surface)',
  ink: 'var(--color-ink)',
  muted: 'var(--color-muted)',
  primary: 'var(--color-primary)',
  primaryHover: 'var(--color-primary-hover)',
  warning: 'var(--color-warning)',
  danger: 'var(--color-danger)',
  border: 'var(--color-border)',
  shadow: 'var(--color-shadow)',
};

export const fonts = {
  display: "'Fraunces', serif",
  body: "'IBM Plex Sans', sans-serif",
};

export const styles = {
  pageBackground: {
    minHeight: '100vh',
    background: colors.bg,
    fontFamily: fonts.body,
  },
  card: {
    background: colors.surface,
    borderRadius: '12px',
    padding: '1.5rem',
    border: `1px solid ${colors.border}`,
    boxShadow: `0 10px 30px ${colors.shadow}`,
  },
  cardAccent: (accentColor) => ({
    background: colors.surface,
    borderRadius: '12px',
    padding: '1.5rem',
    border: `1px solid ${colors.border}`,
    borderLeft: `4px solid ${accentColor}`,
    boxShadow: `0 10px 30px ${colors.shadow}`,
  }),
  pageTitle: {
    fontFamily: fonts.display,
    fontWeight: 600,
    color: colors.ink,
    margin: 0,
  },
  input: {
    width: '100%',
    padding: '0.7rem 0.85rem',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    fontFamily: fonts.body,
    fontSize: '0.95rem',
    color: colors.ink,
    background: colors.surface,
  },
  label: {
    fontSize: '0.85rem',
    fontWeight: 500,
    color: colors.muted,
  },
  buttonPrimary: {
    padding: '0.7rem 1.1rem',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: colors.primary,
    color: '#fff',
    fontWeight: 600,
    fontFamily: fonts.body,
    cursor: 'pointer',
  },
  buttonSecondary: {
    padding: '0.7rem 1.1rem',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    backgroundColor: colors.surface,
    color: colors.ink,
    fontWeight: 600,
    fontFamily: fonts.body,
    cursor: 'pointer',
  },
  buttonDanger: {
    padding: '0.7rem 1.1rem',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: colors.danger,
    color: '#fff',
    fontWeight: 600,
    fontFamily: fonts.body,
    cursor: 'pointer',
  },
  tableCell: {
    padding: '0.85rem 0.6rem',
    verticalAlign: 'top',
    fontFamily: fonts.body,
    color: colors.ink,
  },
  tableHeaderCell: {
    padding: '0.85rem 0.6rem',
    textAlign: 'left',
    fontSize: '0.8rem',
    fontWeight: 600,
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: '0.03em',
    borderBottom: `1px solid ${colors.border}`,
  },
};
